
######################################
# THIS FILE IS AUTOMATICALLY GENERATED FROM PIPS'S SOLUTION
# DO NOT EDIT 
######################################


def policy_ldips(state):
    x = state.get("x_diff")
    v = state.get("v_diff")
    a = state.get("acc")
    #v_self = state.get("v_self")
    #v_front = state.get("v_front")


    ### PIPS LEARNED EXPRESSIONS
    slow_to_fast = ((v > 0.08013299852609634) and ((((v)**2 / a) + x) > 29.55538558959961))
    fast_to_slow = ((v < 0.028881000354886055) and ((((v)**2 / a) - x) > -30.008771896362305))

    ###

    ### GT
    # slow_to_fast = ((v**2)/a + x >  30) and v>0
    # fast_to_slow = ((v**2)/a - x > -30) and v<0
    ###

    pre = state.get("start")
    if pre == "SLOWER":
        if slow_to_fast:
            post = "FASTER"
        else:
            post = "SLOWER"
    elif pre == "FASTER":
        if fast_to_slow:
            post = "SLOWER"
        else:
            post = "FASTER"
    return post
