
######################################
# THIS FILE IS AUTOMATICALLY GENERATED FROM PIPS'S SOLUTION
# DO NOT EDIT 
######################################


def policy_ldips(state):
    x = state.get("x_diff")
    v = state.get("v_diff")
    a = state.get("acc")
    #v_self = state.get("v_self")
    #v_front = state.get("v_front")


    ### PIPS LEARNED EXPRESSIONS
    slow_to_fast = ((v > 0.07844199985265732) and (((x + x) + ((v)**2 / a)) > 49.111053466796875))
    fast_to_slow = ((((v)**2 / a) > 0.002701000077649951) and ((((v)**2 / a) - x) > -29.989704132080078))

    ###

    ### GT
    # slow_to_fast = ((v**2)/a + x >  30) and v>0
    # fast_to_slow = ((v**2)/a - x > -30) and v<0
    ###

    pre = state.get("start")
    if pre == "SLOWER":
        if slow_to_fast:
            post = "FASTER"
        else:
            post = "SLOWER"
    elif pre == "FASTER":
        if fast_to_slow:
            post = "SLOWER"
        else:
            post = "FASTER"
    return post
