
######################################
# THIS FILE IS AUTOMATICALLY GENERATED FROM PIPS'S SOLUTION
# DO NOT EDIT 
######################################


def policy_ldips(state):
    x = state.get("x_diff")
    v = state.get("v_diff")
    a = state.get("acc")
    #v_self = state.get("v_self")
    #v_front = state.get("v_front")


    ### PIPS LEARNED EXPRESSIONS
    slow_to_fast = ((v > -0.018494000658392906) and (((x + x) + ((v)**2 / a)) > 59.944862365722656))
    fast_to_slow = ((v < 0.0351330004632473) and ((((v)**2 / a) - x) > -30.066619873046875))

    ###

    ### GT
    # slow_to_fast = ((v**2)/a + x >  30) and v>0
    # fast_to_slow = ((v**2)/a - x > -30) and v<0
    ###

    pre = state.get("start")
    if pre == "SLOWER":
        if slow_to_fast:
            post = "FASTER"
        else:
            post = "SLOWER"
    elif pre == "FASTER":
        if fast_to_slow:
            post = "SLOWER"
        else:
            post = "FASTER"
    return post
